enable_cameras: true
num_envs: 1
num_demos: 10
step_hz: 20
max_steps: 0
working_path: "~/maniparena_output/recordings/"
format: "hdf5"
teleop_config:
  remote_ip: "10.0.0.100"
  remote_port: 5555
  reconnect_interval: 2.0
  debug: false
stream_viewports:
  width: 640
  height: 480
  position_x: 1280
  position_y: 0
  main_camera: head_camera
  cameras:
    - left_wrist_camera
    - right_wrist_camera
